/*AUTORELACIONAMENTO*/

CREATE DATABASE AUTORELACIONAMENTO;
USE AUTORELACIONAMENTO;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (30),
	HORAS INT,
	VALOR FLOAT(10,2),
	ID_PREREQUISITO INT
);

-- AQUI PODEMOS ABORDAR DE DUAS MANEIRAS
-- OU CRIAMOS UM REGISTRO REFERENTE AO DADO SEM 
-- PRE-REQUISITO E VINCULAMOS TODOS OS CURSOS SEM PRE-REQUITO
--COM ESTE REGISTRO, OU ADICIONAMOS A CONSTRAINT E 
-- DEIXAMOS NULL

-- INSERT INTO CURSOS (1,'SEM PRE-REQUISITO',0,0.0,NULL);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQUISITO
FOREIGN KEY (ID_PREREQUISITO) REFERENCES CURSOS(IDCURSO);

INSERT INTO CURSOS VALUES (NULL, 'BD RELACIONAL', 20,400.00,NULL);
INSERT INTO CURSOS VALUES (NULL, 'BUSINESS INTELLIGENCE', 20,800.00,1);
INSERT INTO CURSOS VALUES (NULL, 'LOGICA PROGRAMACAO', 20,800.00,NULL);
INSERT INTO CURSOS VALUES (NULL, 'JAVA', 20,800.00,3);

SELECT NOME,
	VALOR,
	HORAS,
	IFNULL(ID_PREREQUISITO,"NÃO POSSUI") REQUISITO
FROM CURSOS;
----- JOIN COM ELA MESMA
SELECT C.NOME,
	C.VALOR,
	C.HORAS,
	IFNULL(P.NOME,"---") REQUISITO
FROM CURSOS C
LEFT JOIN CURSOS P 
ON P.IDCURSO = C.ID_PREREQUISITO;

