/*NORMALIZACAO - 2FN E 3FN
	
	PARA SE RESOLVER O PROBLEMA DE RELACIONAMENTOS
	N X N CRIA-SE UMA TABELA ASSOCIATIVA QUE 
	ARMAZENARÁ AS CHAVES DE CADA LADO DO RELACIONAMENTO.
	
	ASSIM ESSA TABELA ASSOCIATIVA POSSUIRÁ UMA CHAVE PRIMÁRIA COMPOSTA
	COM ID DE CADA TABELA QUE ELA SE RELACIONA.
	
	PORÉM UMA CHAVE PRIMARIA DEVE SER ÚNICA,LOGO TENDO UMA CHAVE COMPOSTA INVIABILIZA 
	OS CASOS EM QUE O RELACIONAMENTO PRECISA SE REPETIR.
	
	A 2FN E 3FN RESOLVEM ESSE PROBLEMA.

*/

CREATE DATABASE CONSULTORIO;
USE CONSULTORIO;

CREATE TABLE PACIENTE(
	IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	NASCIMENTO DATE
);

CREATE TABLE MEDICO(
	IDMEDICO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	ESPECIALIDADE VARCHAR(30),
	FUNCIONARIO ENUM('S','N')
	
);

CREATE TABLE HOSPITAL(
	IDHOSPITAL INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	BAIRRO VARCHAR(30),
	CIDADE VARCHAR (30),
	ESTADO CHAR (2)

);

CREATE TABLE CONSULTA(
	IDCONSULTA INT PRIMARY KEY AUTO_INCREMENT,
	ID_PACIENTE INT,
	ID_MEDICO INT,
	ID_HOSPITAL INT,
	DATA DATETIME,
	DIAGNOSTICO VARCHAR(50)
);

CREATE TABLE INTERNACAO(
	IDINTERNACAO INT PRIMARY KEY AUTO_INCREMENT,
	ENTRADA DATETIME,
	QUARTO INT,
	SAIDA DATETIME,
	OBSERVACOES VARCHAR(50),
	ID_CONSULTA INT UNIQUE	
);  

/*MODELAGEM COM ENDERECO SEPARADO*/
/*CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	BAIRRO VARCHAR(30),
	CIDADE VARCHAR (30),
	ESTADO CHAR (2),
	ID_PACIENTE	INT,
	ID_HOSPITAL INT
);						  

CREATE TABLE PACIENTE(
	IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	NASCIMENTO DATE
);

CREATE TABLE HOSPITAL(
	IDHOSPITAL INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30)
);

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_PACIENTE
FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE);

ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_HOSPITAL
FOREIGN KEY(ID_HOSPITAL) REFERENCES HOSPITAL(IDHOSPITAL);*/

/* CRIANDO AS CONSTRAINTS*/

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_PACIENTE
FOREIGN KEY(ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_MEDICO
FOREIGN KEY(ID_MEDICO) REFERENCES MEDICO(IDMEDICO);

ALTER TABLE CONSULTA ADD CONSTRAINT FK_CONSULTA_HOSPITAL
FOREIGN KEY(ID_HOSPITAL) REFERENCES HOSPITAL(IDHOSPITAL);

ALTER TABLE INTERNACAO ADD CONSTRAINT FK_INTERNACAO_CONSULTA
FOREIGN KEY(ID_CONSULTA) REFERENCES CONSULTA(IDCONSULTA);