/*NORMALIZACAO*/

/*
1ª FORMA NORMAL

A- TODO CAMPO VETORIZADO SE TORNARA OUTRA TABELA
VETORES = ELEMENTOS(LISTA) DE UM MESMO TIPO
[AZUL,AMARELO,VERDE] - VETOR DE CORES
[KA,FIT,FIESTA] - VETOR DE CARROS

B- TODO CAMPO MULTIVALORADA SE TORNARA OUTRA TABELA 
CAMPOS MULTIVALORADOS SAO AQUELES QUE RECEBEM MUITOS VALORES,
PORÉM NÃO SÃO DO MESMO TIPO.
EX: UMA TABELA QUE POSSUI UM CAMPO ENDERECO
ENDERECO = RUA GLICERIO, CENTRO, CAMPINAS - SP
CLARAMENTE PODEMOS NOTAR QUE ESTA TABELA, POSSUI VARIOS VALORES DISTINTOS.
NELA TEMOS UMA RUA, UM BAIRO, UMA CIDADE E UM ESTADO.

 
C- TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE TODO
REGISTRO COMO SENDO UNICO (CHAVE PRIMÁRIA - PRIMARY KEY)
EXITEM DOIS TIPOS DE CHAVES:
C.1) NATURAL (EX: TABELA QUE POSSUI UM CAMPO CPF)
C.2) ARTIFICIAL (EX: ID)

*/

/*FOREIGN KEY - CHAVE ESTRANGEIRA
É A CHAVE PRIMARIA DE UMA TABELA, QUE VAI ATÉ OUTRA TABELA FAZER REFERENCIA 
DO RELACIONAMENTO
*/

/*EM RELACIONAMENTOS 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA*/
/*EM RELACIONAMENTOS 1 X N A CHAVE ESTRANGEIRA FICARA SEMPRE NA TABELA N*/


/*NOVA MODELAGEM DA TABELA CLIENTE*/
CREATE DATABASE COMERCIO;
USE COMERCIO;

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (30) NOT NULL,
	SEXO ENUM ('M','F') NOT NULL,
	EMAIL VARCHAR (50) UNIQUE,
	CPF VARCHAR (15) UNIQUE 	

);

CREATE TABLE TELEFONE (
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM ('COM','RES','CEL'),
	NUMERO VARCHAR (10),
	ID_CLIENTE INT,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR (30) NOT NULL,
	BAIRRO VARCHAR (30) NOT NULL,
	CIDADE VARCHAR (30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY (ID_CLIENTE)
	REFERENCES CLIENTE (IDCLIENTE)
);

/*POPULAR AS TABELAS*/
/*CLIENTE*/
INSERT INTO CLIENTE VALUES (NULL,'JOAO','M','JOAO@GMAIL.COM',22426071702);
INSERT INTO CLIENTE VALUES (NULL,'JOSE','M','JOSE@GMAIL.COM',12240928212);
INSERT INTO CLIENTE VALUES (NULL,'MARIO','F','MARIO@GMAIL.COM',80474078485);
INSERT INTO CLIENTE VALUES (NULL,'MARIA','F','MARIA@GMAIL.COM',17937101202);
INSERT INTO CLIENTE VALUES (NULL,'JOSEFINA','F','JOSEFINA@GMAIL.COM',47721441293);
INSERT INTO CLIENTE VALUES (NULL,'ANGELA','M','ANGELA@GMAIL.COM',25681521419);
/*ENDERECO*/
INSERT INTO ENDERECO VALUES (NULL,'RUA A','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO VALUES (NULL,'RUA B','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO VALUES (NULL,'RUA C','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO VALUES (NULL,'RUA D','CENTRO','BELO HORIZONTE','MG',6);
INSERT INTO ENDERECO VALUES (NULL,'RUA E','CAMBUI','CAMPINAS','SP',4);
INSERT INTO ENDERECO VALUES (NULL,'RUA F','CENTRO','CAMPINAS','SP',5);
/*TELEFONE*/
INSERT INTO TELEFONE VALUES (NULL,'CEL',9998889,3);
INSERT INTO TELEFONE VALUES (NULL,'RES',99987889,3);
INSERT INTO TELEFONE VALUES (NULL,'COM',11987889,1);
INSERT INTO TELEFONE VALUES (NULL,'COM',97887889,2);
INSERT INTO TELEFONE VALUES (NULL,'COM',7787889,6);
INSERT INTO TELEFONE VALUES (NULL,'COM',55987889,5);

/*SELECAO, PROJECAO E JUNCAO*/
/*PODE-SE DIZER QUE A PROJECAO SE DA NA VERTICAL (COLUNA) E A SELECAO SE DA NA HORIZONTAL (TUPLA/LINHA)*/
/*PROJECAO - TUDO O QUE QUEREMOS PROJETAR (PODE EXISTIR A COLUNA OU NAO)*/
SELECT NOW() AS "DATA ATUAL";
SELECT NOME,NOW() AS "PESQUISA FEITA EM:" FROM CLIENTE;

/*SELECAO - TEORIA DOS CONJUNTOS (SELECIONAR UM SUB-CONJUNTO DE UM CONJUNTO INTEIRO)*/
SELECT NOME,SEXO FROM CLIENTE;
SELECT NOME,SEXO FROM CLIENTE 
WHERE SEXO = 'M';/*WHERE É CONSIDERADO UMA CLAUSULA DE SELECAO*/

/*JUNCAO - "ERRADA"*/
SELECT NOME,SEXO,BAIRRO,CIDADE,NOW() AS "DATA"
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE /*WHERE É CONSIDERADO UMA CLAUSULA DE SELECAO NAO USAR PARA JUNCAO*/
AND BAIRRO LIKE '%CENTRO%'; 

/*JUNCAO - JOIN*/
SELECT NOME,SEXO,BAIRRO,CIDADE /*PROJECAO*/
FROM CLIENTE 
INNER JOIN ENDERECO /*JUNCAO*/
ON IDCLIENTE = ID_CLIENTE 
WHERE BAIRRO LIKE '%CENTRO%'; /*SELECAO*/

SELECT CLIENTE.NOME,CLIENTE.SEXO,
ENDERECO.BAIRRO,ENDERECO.CIDADE,
TELEFONE.TIPO,TELEFONE.NUMERO /*PROJECAO*/
FROM CLIENTE 
INNER JOIN ENDERECO /*JUNCAO*/
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE 
INNER JOIN TELEFONE /*JUNCAO*/
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

SELECT C.NOME,
		C.SEXO,IFNULL(C.EMAIL,'SEM EMAIL') AS EMAIL,
		E.BAIRRO,
		E.CIDADE,
		T.TIPO,
		T.NUMERO /*PROJECAO*/
FROM CLIENTE C
INNER JOIN ENDERECO E/*JUNCAO*/
ON C.IDCLIENTE = E.ID_CLIENTE 
INNER JOIN TELEFONE T /*JUNCAO*/
ON C.IDCLIENTE = T.ID_CLIENTE
WHERE C.SEXO = 'M'; /*SELECAO*/
/*DICA: BOTAO DIREITO NA TELA->MARCAR, SELECIONA COM BOTAO ESQUERDO; AO FINAL BOTAO DIREITO NOVAMENTE, E O CONTEUDO SERA COPIADO*/
+--------+------+------------------+---------+----------------+------+----------
+
| NOME   | SEXO | EMAIL            | BAIRRO  | CIDADE         | TIPO | NUMERO
|
+--------+------+------------------+---------+----------------+------+----------
+
| JOAO   | M    | JOAO@GMAIL.COM   | CENTRO  | RIO DE JANEIRO | COM  | 11987889
|
| JOSE   | M    | SEM EMAIL        | ESTACIO | RIO DE JANEIRO | COM  | 97887889
|
| ANGELA | M    | ANGELA@GMAIL.COM | CENTRO  | BELO HORIZONTE | COM  | 7787889
|
+--------+------+------------------+---------+----------------+------+----------

/*ORDER BY*/
SELECT NOME,SEXO,CPF,CIDADE
FROM CLIENTE
INNER JOIN ENDERECO 
ON IDCLIENTE = ID_CLIENTE
ORDER BY NOME ASC;

SELECT NOME,SEXO,CPF,CIDADE
FROM CLIENTE
INNER JOIN ENDERECO 
ON IDCLIENTE = ID_CLIENTE
ORDER BY NOME DESC;

SELECT NOME,SEXO,CPF,CIDADE
FROM CLIENTE
INNER JOIN ENDERECO 
ON IDCLIENTE = ID_CLIENTE
ORDER BY 4; /*ORDENA PELA 4º COLUNA*/

