/*modelagem basica*/

CLIENTE
nome
cpf
email
telefone
sexo
endereco

/*processo modelagem*/
/*modelagem conceitual - rascunho*/
/*modelagem logica - programas como brmodelo*/
/*modelagem fisica - script do banco*/

/*CRIANDO UM BANCO*/
CREATE DATABASE PROJETO;

/*MOTRANDO OS BANCOS*/
SHOW DATABASES;

/*CONECTAR E USAR O BANCO*/
USE PROJETO;

/*CRIANDO A TABELA*/
CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)	
);

/*VISUALIZANDO TABELAS - APENAS MYSQL*/
SHOW TABLES;

/*DESCREVENDO AS TABELAS*/
DESC CLIENTE;
/********************************************************/
/*INSERIR - EXISTEM 3 FORMAS DE ESCREVER*/
INSERT INTO CLIENTE VALUES ('JOSE DA SILVA','M','JOSE@GMAIL.COM',391787734,'999999999','RUA TESTE');
INSERT INTO CLIENTE VALUES ('PEDRO DA SILVA','M','PEDRO@GMAIL.COM',491788735,'881119999','RUA TESTE2');

INSERT INTO CLIENTE (NOME,SEXO,EMAIL,CPF,TELEFONE,ENDERECO) VALUES ('MARIA JOAQUINA','F','MARIA@GMAIL.COM',591797734,'119966699','RUA TESTE3');
/* APENAS MYSQL*/
INSERT INTO CLIENTE VALUES ('PEDRITA JOANA','F','PJOANA@GMAIL.COM',591755734,'179966699','RUA TESTE4'),
							('ANA SILVA','F',NULL,691557734,'819966699','RUA TESTE5');
/********************************************************/
/*SELECIONAR*/
/*MYSQL - TRAZ A DATA ATUAL*/
SELECT NOW();
/*TRAZ USUARIO ATUAL*/
SELECT CURRENT_USER();

SELECT * FROM CLIENTE;
SELECT NOME,EMAIL,CPF FROM CLIENTE;
/*FILTROS WHERE*/
SELECT NOME,EMAIL,CPF FROM CLIENTE WHERE SEXO = 'M';
/*FILTROS LIKE*/
/*CARACTER CORINGA % = TUDO ANTES / TUDO APOS / TUDO QUE CONTENHA*/
/*COMEÇA COM QUALQUER COISA E TERMINA COM SILVA*/
SELECT NOME,EMAIL,CPF FROM CLIENTE WHERE NOME LIKE '%SILVA';
/*CONTENHA JOANA*/
SELECT NOME,EMAIL,CPF FROM CLIENTE WHERE NOME LIKE '%JOANA%';
/*FILTRANDO VALORES NULOS*/
SELECT NOME,CPF FROM CLIENTE 
WHERE EMAIL IS NULL;

SELECT NOME,CPF FROM CLIENTE 
WHERE EMAIL IS NOT NULL;

/*OPERADORES LOGICOS*/
/*OR - OU*/
SELECT NOME,EMAIL,CPF FROM CLIENTE WHERE SEXO = 'M'
OR ENDERECO LIKE '%TESTE1%';

/*AND - E*/
SELECT NOME,EMAIL,CPF FROM CLIENTE WHERE SEXO = 'M'
AND ENDERECO LIKE '%TESTE1%';

/*CONTAR OS REGISTROS DAS TABELAS*/
SELECT COUNT(*) FROM CLIENTE;
SELECT COUNT(*) AS "QTD_CLIENTES "FROM CLIENTE;
/*GROUP BY*/
SELECT SEXO,COUNT(*) AS "QTD_CLIENTES_POR_SEXO"
FROM CLIENTE GROUP BY SEXO;
/********************************************************/
/*UPDATE*/
UPDATE CLIENTE SET NOME = 'Nome atualizado' WHERE NOME = 'JOSE DA SILVA';
/********************************************************/
/*DELETE*/
DELETE FROM CLIENTE WHERE NOME = 'Nome atualizado';