/*BACKUP LÓGICO COM TRIGGERS*/
/*COMUNICACAO ENTRE BANCOS DIFERENTES

BANCO.ESQUEMA.TABELA

*/

CREATE DATABASE LOJA;
USE LOJA;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (30),
	VALOR FLOAT(10,2)
);

CREATE DATABASE LOJA_BACKUP;
USE LOJA_BACKUP;

CREATE TABLE PRODUTO_BKP(
	IDPRODUTO_BKP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR (30),
	VALOR FLOAT(10,2),
	EVENTO VARCHAR (10)
);

USE LOJA;

/*1 - MUDA O DELIMITADOR*/
DELIMITER $

/*2 - CRIA-SE A TRIGGER PARA INSERT*/
CREATE TRIGGER BACKUP_USUARIO_INSERT
AFTER INSERT ON PRODUTO
FOR EACH ROW 
BEGIN  
		INSERT INTO LOJA_BACKUP.PRODUTO_BKP VALUES
		(NULL,NEW.IDPRODUTO,NEW.NOME,NEW.VALOR,"INSERIDO");
END 
$

/*3 - VOLTA-SE O DELIMITADOR PARA O PADRAO*/
DELIMITER ;

INSERT INTO PRODUTO VALUES (NULL,'LIVRO MODELAGEM',50.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO BI',70.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO ORACLE',90.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO SQL SERVER',40.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO JAVA USE A CABECA',60.00);

SELECT * FROM PRODUTO;
SELECT * FROM LOJA_BACKUP.PRODUTO_BKP;

/*1 - MUDA O DELIMITADOR*/
DELIMITER $

/*2 - CRIA-SE A TRIGGER PARA DELETE*/
CREATE TRIGGER BACKUP_USUARIO_DELETE
BEFORE DELETE ON PRODUTO
FOR EACH ROW 
BEGIN  
		INSERT INTO LOJA_BACKUP.PRODUTO_BKP VALUES
		(NULL,OLD.IDPRODUTO,OLD.NOME,OLD.VALOR,"DELETADO");
END 
$

/*3 - VOLTA-SE O DELIMITADOR PARA O PADRAO*/
DELIMITER ;

DELETE FROM PRODUTO WHERE IDPRODUTO = 2;
SELECT * FROM LOJA_BACKUP.PRODUTO_BKP;

/*AUDITORIA DE DADOS*/

DROP DATABASE LOJA;
DROP DATABASE LOJA_BACKUP;

CREATE DATABASE LOJA;
USE LOJA;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (30),
	VALOR FLOAT(10,2)
);

INSERT INTO PRODUTO VALUES (NULL,'LIVRO MODELAGEM',50.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO BI',70.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO ORACLE',90.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO SQL SERVER',40.00);
INSERT INTO PRODUTO VALUES (NULL,'LIVRO JAVA USE A CABECA',60.00);

SELECT * FROM PRODUTO;

CREATE DATABASE LOJA_BACKUP;
USE LOJA_BACKUP;

CREATE TABLE PRODUTO_BKP(
	IDPRODUTO_BKP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR (30),
	VALOR_ORIGINAL FLOAT(10,2),
	VALOR_ALTERADO FLOAT(10,2),
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO VARCHAR (10)
);

USE LOJA;

/*1 - MUDA O DELIMITADOR*/
DELIMITER $

/*2 - CRIA-SE A TRIGGER PARA UPDATE*/
CREATE TRIGGER AUDIT_PRODUTO
AFTER UPDATE ON PRODUTO
FOR EACH ROW 
BEGIN  
		INSERT INTO LOJA_BACKUP.PRODUTO_BKP VALUES
		(NULL,OLD.IDPRODUTO,OLD.NOME,
			OLD.VALOR,NEW.VALOR,NOW(),CURRENT_USER(),"ATUALIZADO");
END 
$

/*3 - VOLTA-SE O DELIMITADOR PARA O PADRAO*/
DELIMITER ;


UPDATE PRODUTO SET VALOR = 115.50 
WHERE IDPRODUTO = 2;

SELECT * FROM LOJA_BACKUP.PRODUTO_BKP;
