/*CURSORES*/

CREATE DATABASE CURSORES;
USE CURSORES;

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT

);

INSERT INTO VENDEDORES VALUES (NULL,'PEDRO',23523,45487,1247);
INSERT INTO VENDEDORES VALUES (NULL,'JOAO',23523,8854,325788);
INSERT INTO VENDEDORES VALUES (NULL,'MARIA',998,95478,7986541);
INSERT INTO VENDEDORES VALUES (NULL,'PEDRO',7895,7848,55);

/*JEITO PADRAO DE SE TRABALHAR COM FUNCOES DE AGREGACAO EM LINHAS*/
/*PORÉM SE A TABELA FOR MUITO GRANDE, PODE-SE PERDER TEMPO E PROCESSAMENTO*/
SELECT 	NOME, 
		(JAN+FEV+MAR) AS TOTAL, 
		(JAN+FEV+MAR)/3 AS MEDIA 
FROM VENDEDORES;

/*UMA DAS SOLUCOES SERIA USAR CURSORES PARA ESTA OPERACAO
 CRIA-SE UMA TABELA INTERMEDIARIA PARA ARMAZENAR OS CALCULOS
*/

CREATE TABLE VENDA_TOTAL(
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MAR INT,
	TOTAL INT,
	MEDIA INT
);

/*O CURSOR É COMO UMA PROGRAMACAO DENTRO DE UMA PROCEDURE*/

DELIMITER $

CREATE PROCEDURE CALCULAVENDAS()
BEGIN
	/*VARIAVEL*/
	DECLARE FIM INT DEFAULT 0;
	DECLARE VAR1,VAR2,VAR3,VTOTAL,VMEDIA INT;
	DECLARE VNOME VARCHAR(50);
	
	/*VARIAVEL - VETOR, NAO PRECISA DECLARAR O TAMANHO*/
	DECLARE VETORREG CURSOR FOR(
	/*O VETOR SERA PREENCHIDO COM OS VALORES DA QUERY
		NAO SE USA ; NA QUERY DENTRO DO CURSOR, POIS A QUERY É CONSIDERADA
		COM UMA VARIAVEL*/
		SELECT NOME,JAN,FEV,MAR FROM VENDEDORES
	);
	
	/*VARIAVEL QUE CONTROLA O LAÇO DO LOOP*/
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
	
	/*ARMAZENA O VALOR DO VETOR E ALOCA NA MEMORIA RAM
		PARA QUE SEJA POSSIVEL EXECUTAR MANIPULACOES
	*/
	OPEN VETORREG;	
	/*O LOOP SE INICIA - ITERA DENTRO DO VETOR PEGANDO CADA LINHA DO REGISTRO E ACESSANDO CADA COLUNA*/
	REPEAT
	/*PEGA O PROXIMO VALOR DO VETOR - QUE FUI PUXADO PELA QUERY EXECUTADA DENTRO DA DECLARACAO DO VETOR LINHA 52*/
		FETCH VETORREG INTO VNOME,VAR1,VAR2,VAR3;
		IF NOT FIM THEN 
			/*ATRIBUI VALORES*/
			SET VTOTAL = VAR1+VAR2+VAR3;
			SET VMEDIA = VTOTAL/3;
			/*INSERE NA TABELA*/	
			INSERT INTO VENDA_TOTAL VALUES(VNOME,VAR1,VAR2,VAR3,VTOTAL,VMEDIA);
		END IF;
	/*FECHA O LOOP*/	
	UNTIL FIM END REPEAT;
	/*FECHA O CURSOR E LIMPA A MEMORIA RAM*/
	CLOSE VETORREG;
	
END
$

DELIMITER ;

/*PARA SE CHAMAR UM CURSOR, USA-SE A MESMA CHAMADA DE PROCEDURE*/
CALL CALCULAVENDAS();

SELECT * FROM VENDA_TOTAL;

/* TRIGGERS COM VARIAVEIS */

DELIMITER $

CREATE TRIGGER CADTOTAL
BEFORE INSERT ON VENDEDORES
FOR EACH ROW
BEGIN
		DECLARE VTOTAL, VMEDIA INT;
		
		SET VTOTAL := NEW.JAN + NEW.FEV + NEW.MAR;
		SET VMEDIA := (NEW.JAN + NEW.FEV + NEW.MAR)/3;
		
		INSERT INTO VENDA_TOTAL VALUES(NEW.NOME,NEW.JAN,NEW.FEV,NEW.MAR,VTOTAL,VMEDIA);

END
$

DELIMITER ;

INSERT INTO VENDEDORES VALUES(NULL,'JULIO',9999,9999,9999);
						  
SELECT * FROM VENDEDORES;
SELECT * FROM VENDA_TOTAL;