/*FUNCOES DE AGREGACAO NUMERICA*/

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR (30),
	SEXO CHAR (1),
	JANEIRO FLOAT (10,2),
	FEVEREIRO FLOAT (10,2),
	MARCO FLOAT (10,2)

);

INSERT INTO VENDEDORES
VALUES (NULL,'CARLOS','M',8487.56,457487.56,14578.66);
INSERT INTO VENDEDORES
VALUES (NULL,'MANUEL','M',9487.56,457487.56,12458.66);
INSERT INTO VENDEDORES
VALUES (NULL,'PATRICIA','F',49987.56,457487.56,12578.66);
INSERT INTO VENDEDORES
VALUES (NULL,'FERNANDA','F',45997.56,457487.56,12478.66);
INSERT INTO VENDEDORES
VALUES (NULL,'HENRIQUE','M',414487.56,457487.56,124668.66);
INSERT INTO VENDEDORES
VALUES (NULL,'MARIA','F',40487.56,457487.56,1678.66);
INSERT INTO VENDEDORES
VALUES (NULL,'GLAUCIA','F',45007.56,457487.56,1778.66);

/*ESTAS FUNCOES FUNCIONAM APENAS EM NIVEL DE COLUNA*/
/*MAX - RETORNA O VALOR MAXIMO DE UMA COLUNA*/
SELECT MAX(FEVEREIRO) AS "MAIOR_FEVEREIRO"
FROM VENDEDORES;

/*MIN - RETORNA O VALOR MINIMO DE UMA COLUNA*/
SELECT MIN(FEVEREIRO) AS "MENOR_FEVEREIRO"
FROM VENDEDORES;

/*AVG - RETORNA O VALOR MEDIO DE UMA COLUNA*/
SELECT AVG(FEVEREIRO) AS "MEDIA_FEVEREIRO"
FROM VENDEDORES;

/*JUNTAS + TRUNCATE ()*/
SELECT MAX(JANEIRO) AS "MAX_JANEIRO",
		MIN(JANEIRO) AS "MIN JANEIRO",
		TRUNCATE(AVG(JANEIRO),2) AS "MEDIA_JANEIRO"
FROM VENDEDORES;


/*SUM*/
SELECT SUM(JANEIRO) AS "TOTAL JANEIRO" FROM VENDEDORES;
SELECT SUM(JANEIRO) AS "TOTAL JANEIRO",
		SUM(FEVEREIRO) AS "TOTAL FEVEREIRO",
		SUM(MARCO) AS "TOTAL MARCO"
 FROM VENDEDORES;
 
 SELECT SEXO,SUM(JANEIRO) AS "TOTAL JANEIRO" 
 FROM VENDEDORES GROUP BY SEXO;
 
 /*SUBQUERY (INNER QUERY,SUBSELECT...):
 
 A)VENDEDOR QUE VENDEU MENOS EM JANEIRO E O SEU NOME
 B)VENDERDOR QUE VENDEU MAIS EM JANEIRO E O SEU NOME
 C)QUEM VENDEU MAIS QUE O VALOR MEDIO DE JANEIRO
 D)QUEM VENDEU MENOS QUE O VALOR MEDIO DE JANEIRO
 
 */
 
 SELECT NOME, JANEIRO FROM VENDEDORES
 WHERE JANEIRO = (SELECT MIN(JANEIRO) FROM VENDEDORES);
 
 SELECT NOME, JANEIRO FROM VENDEDORES
 WHERE JANEIRO = (SELECT MAX(JANEIRO) FROM VENDEDORES);
 
 SELECT NOME, JANEIRO FROM VENDEDORES
 WHERE JANEIRO > (SELECT AVG(JANEIRO) FROM VENDEDORES);
 
 SELECT NOME, JANEIRO FROM VENDEDORES
 WHERE JANEIRO < (SELECT AVG(JANEIRO) FROM VENDEDORES);
 
 /*FUNCOES EM NIVEL DE LINHA NAO EXISTEM, PRECISAMOS FAZER PROJECOES*/
 /*EXTRAINDO OS VALORES TOTAIS DE CADA VENDEDOR E SUA MEDIA*/
 SELECT NOME, 	
		JANEIRO, 
		FEVEREIRO, 
		MARCO,
		(JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
		TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS "MEDIA"
 FROM VENDEDORES ORDER BY TOTAL DESC;
 
  /*EXTRAINDO OS VALORES TOTAIS DE CADA VENDEDOR E SUA MEDIA E A SUA COMISSAO*/
 SELECT NOME, 	
		JANEIRO, 
		FEVEREIRO, 
		MARCO,
		(JANEIRO+FEVEREIRO+MARCO) AS "TOTAL",
		TRUNCATE((JANEIRO+FEVEREIRO+MARCO)/3,2) AS "MEDIA",
		(JANEIRO+FEVEREIRO+MARCO) * 0.06 AS "COMISSAO"
 FROM VENDEDORES ORDER BY TOTAL DESC;
 