/*ALTERANDO A TABELA*/
CREATE TABLE TABELA (
	COLUNA1 VARCHAR(30),
	COLUNA2 VARCHAR(30),
	COLUNA3 VARCHAR(30)
	
);

-- ADICIONAR PK
ALTER TABLE TABELA
ADD PRIMARY KEY (COLUNA1);

-- ADICIONAR COLUNA (AUTOMATICAMENTE NA ULTIMA POSICAO)
ALTER TABLE TABELA
ADD COLUNA VARCHAR(30);

-- ADICIONAR COLUNA COM POSICAO
ALTER TABLE TABELA
ADD COLUMN COLUNA4 VARCHAR (30) NOT NULL UNIQUE
AFTER COLUNA3;

-- MODIFICAR O TIPO DE UM CAMPO (SE A COLUNA ESTIVER POPULADA, SÓ SERÁ POSSÍVEL
-- SE O NOVO TIPO FOR IGUAL AO QUE JÁ ESTA NA COLUNA)
ALTER TABLE TABELA 
MODIFY COLUNA2 DATE NOT NULL;

-- RENOMEAR O NOME DA TABELA
ALTER TABLE TABELA RENAME PESSOA;

CREATE TABLE TIME(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	TIME VARCHAR(30),
	ID_PESSOA VARCHAR(30)
);
-- ADICIONAR FOREIGN KEY
ALTER TABLE TIME
ADD FOREIGN KEY (ID_PESSOA)
REFERENCES PESSOA(COLUNA1);

/*VERIFICAR AS CHAVES*/
SHOW CREATE TABLE PESSOA;
SHOW CREATE TABLE TIME;

/*| TIME  | CREATE TABLE `time` (
  `IDTIME` int(11) NOT NULL AUTO_INCREM
  `TIME` varchar(30) DEFAULT NULL,
  `ID_PESSOA` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`IDTIME`),
  KEY `ID_PESSOA` (`ID_PESSOA`),
  CONSTRAINT `time_ibfk_1` FOREIGN KEY -- NOME ALEATÓRIO DADO PELO BANCO
A1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |*/

/*CONSTRAINTS*/
-- ADICIONAR A CRIAÇÃO DE CHAVES FORA DO SCRIPT DE CREATE
-- PARA QUE POSSAMOS NOMEAR CORRETAMENTE AS CONSTRAINTS
-- E SEGUIR AS BOAS PRÁTICAS DEIXANDO NOS PRIMEIROS BLOCOS APENAS A CRIAÇÃO
-- E NOS SEGUNDOS BLOCOS AS ALTERACOES COM A ADICAO DAS CONSTRAINTS (CHAVES)
DROP TABLE ENDERECO;
DROP TABLE TELEFONE;
DROP TABLE CLIENTE;

CREATE TABLE CLIENTE(
	IDCLIENTE INT,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT,
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR (10) NOT NULL,
	ID_CLIENTE INT
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY (IDCLIENTE);

-- FK_TABELAONDESERAARMAZENADO_TABELAORIGEM
ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_CLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (IDCLIENTE);

SHOW CREATE TABLE TELEFONE;
/*| TELEFONE | CREATE TABLE `telefone` (
  `IDTELEFONE` int(11) DEFAULT NULL,
  `TIPO` char(3) NOT NULL,
  `NUMERO` varchar(10) NOT NULL,
  `ID_CLIENTE` int(11) DEFAULT NULL,
  KEY `FK_CLIENTE_TELEFONE` (`ID_CLIENTE`),
  CONSTRAINT `FK_CLIENTE_TELEFONE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `client
e` (`IDCLIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 |*/