/*DICIONARIO DE DADOS*/
-- EXISTEM DICIONARIOS PADROES NO SISTEMA QUE GUARDAM METADADOS SOBRE AS TABELAS
SHOW DATABASES;
+--------------------+
| Database           |
+--------------------+
| information_schema | -- DICIONARIO
| comercio           |
| livro              |
| mysql              | -- DICIONARIO
| performance_schema | -- DICIONARIO
| projeto            |
| sys                |
+--------------------+

USE INFORMATION_SCHEMA;

SHOW TABLES;

DESC TABLE_CONSTRAINTS;

SELECT * FROM TABLE_CONSTRAINTS 
WHERE CONSTRAINT_SCHEMA = 'COMERCIO';

SELECT CONSTRAINT_SCHEMA AS "BANCO",
	TABLE_NAME AS "TABELA",
	CONSTRAINT_NAME AS "NOME REGRA",
	CONSTRAINT_TYPE AS "TIPO"
FROM TABLE_CONSTRAINTS 
WHERE CONSTRAINT_SCHEMA = 'COMERCIO';

/*APAGAR CONSTRAINTS*/
USE COMERCIO;

ALTER TABLE TELEFONE
DROP FOREIGN KEY FK_CLIENTE_TELEFONE;

-- ADICIONA NOVAMENTE
ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (IDCLIENTE);

/*ESTAS DUAS ULTIMAS ACOES PODEM SER BOAS 
QUANDO PRECISA-SE INSERIR DADOS EM MASSA
SEM A CONSTRAINT O BANCO NAO CHECARA SE O REGISTRO INSERIDO 
POSSUI OU NAO REFERENCIAS EM OUTRA DETERMINADA TABELA
NAO ESQUECER DE ATIVAR A CONSTRAINT NOVAMENTE!!!!!!
*/

	
	